name: ci

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build -t base-image -f etc/base.dockerfile .
      - run: docker build -t tmp -f etc/final.dockerfile .
      - run: docker run tmp --help
